# Feature Engineering

## Objective

In this notebook we prepare the cleaned dataset for Machine Learning.

Steps:

- Feature Selection
- Encoding
- Feature Scaling
- Train-Test Split
- Save processed data

In [21]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

import os

os.makedirs("../models", exist_ok=True)

import pickle

In [2]:
df = pd.read_csv("../data/clean_telco.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

## Separate Input and Target Variables

Target Variable:

- Churn

Input Variables:

- Remaining columns

In [5]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [6]:
print(X.shape)
print(y.shape)

(7032, 20)
(7032,)

In [7]:
label_encoder = LabelEncoder()

y = label_encoder.fit_transform(y)

In [8]:
pd.Series(y).value_counts()

0    5163
1    1869
Name: count, dtype: int64

In [9]:
categorical_columns = X.select_dtypes(include="object").columns

categorical_columns

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod'],
      dtype='object')

In [10]:
X = pd.get_dummies(
    X,
    columns=categorical_columns,
    drop_first=True
)

In [11]:
X.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,customerID_0003-MKNFE,customerID_0004-TLHLJ,customerID_0011-IGKFF,customerID_0013-EXCHZ,customerID_0013-MHZWF,customerID_0013-SMEOE,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False

In [12]:
X.shape

(7032, 7061)

## Train Test Split

Training Data = 80%

Testing Data = 20%

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [14]:
print(X_train.shape)
print(X_test.shape)

(5625, 7061)
(1407, 7061)

In [15]:
scaler = StandardScaler()

In [16]:
numerical_columns = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

In [17]:
X_train[numerical_columns] = scaler.fit_transform(
    X_train[numerical_columns]
)

In [18]:
X_test[numerical_columns] = scaler.transform(
    X_test[numerical_columns]
)

In [19]:
X_train.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,customerID_0003-MKNFE,customerID_0004-TLHLJ,customerID_0011-IGKFF,customerID_0013-EXCHZ,customerID_0013-MHZWF,customerID_0013-SMEOE,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
1408,0,1.321816,0.981556,1.659900,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False
6992,0,-0.267410,-0.971546,-0.562252,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3349,0,1.444064,0.837066,1.756104,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False
4486,0,-1.204646,0.641092,-0.908326,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
3535,0,0.669826,-0.808787,-0.101561,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [22]:
with open("../models/scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

print("Scaler Saved!")

Scaler Saved!

In [23]:
with open("../models/label_encoder.pkl","wb") as file:
    pickle.dump(label_encoder,file)

print("Label Encoder Saved!")

Label Encoder Saved!

In [24]:
X_train.to_csv("../data/X_train.csv", index=False)
X_test.to_csv("../data/X_test.csv", index=False)

pd.Series(y_train).to_csv("../data/y_train.csv", index=False)
pd.Series(y_test).to_csv("../data/y_test.csv", index=False)

In [25]:
print("Processed datasets saved successfully!")

Processed datasets saved successfully!

In [26]:
feature_names = X.columns

feature_names

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'customerID_0003-MKNFE', 'customerID_0004-TLHLJ',
       'customerID_0011-IGKFF', 'customerID_0013-EXCHZ',
       'customerID_0013-MHZWF', 'customerID_0013-SMEOE',
       ...
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object', length=7061)

In [27]:
len(feature_names)

7061

In [28]:
with open("../models/feature_names.pkl","wb") as file:
    pickle.dump(feature_names,file)

print("Feature Names Saved!")

Feature Names Saved!

In [29]:
print("="*50)

print("Feature Engineering Completed")

print("="*50)

print("Training Samples :",X_train.shape)

print("Testing Samples :",X_test.shape)

print("Total Features :",X_train.shape[1])

print("="*50)

==================================================
Feature Engineering Completed
==================================================
Training Samples : (5625, 7061)
Testing Samples : (1407, 7061)
Total Features : 7061
==================================================

# Output

Generated Files:

- X_train.csv
- X_test.csv
- y_train.csv
- y_test.csv
- scaler.pkl
- label_encoder.pkl
- feature_names.pkl

These files will be used in the next notebook for Machine Learning model training.